#ifndef CPUSTATS_KEYS_H
#define CPUSTATS_KEYS_H

//***SMC ACCESS KEYS

#define KERNEL_INDEX_SMC 2
#define SMC_CMD_READ_BYTES 5
#define SMC_CMD_WRITE_BYTES 6
#define SMC_CMD_READ_INDEX 8
#define SMC_CMD_READ_KEYINFO 9
#define SMC_CMD_READ_PLIMIT 11
#define SMC_CMD_READ_VERS 12


//***DATA TYPES

#define DATATYPE_FLT "flt "
#define DATATYPE_FPE2 "fpe2"
#define DATATYPE_UINT8 "ui8 "
#define DATATYPE_UINT16 "ui16"
#define DATATYPE_SINT16 "si16"
#define DATATYPE_UINT32 "ui32"
#define DATATYPE_SP78 "sp78"
#define DATATYPE_FP88 "fp88"
#define DATATYPE_SP96 "sp96"
#define DATATYPE_CH8 "ch8*"
#define DATATYPE_FLAG "flag"
#define DATATYPE_SP96 "sp96"
#define DATATYPE_HEX "hex_"

//DATA TYPE SIZE
#define DATATYPE_FLT_DATASIZE 4

//***CPU
//TEMPERAURE

#define SMC_KEY_CPU_TEMP_CORE_AVG "TC0P" //AVERAGE
#define SMC_KEY_CPU_TEMP_CORE_PECI "TCXC" //PECI
#define SMC_KEY_CPU_TEMP_CORE1 "TC1C" //CORE 1
#define SMC_KEY_CPU_TEMP_CORE2 "TC2C" //CORE 2
#define SMC_KEY_CPU_TEMP_CORE3 "TC3C" //CORE 3
#define SMC_KEY_CPU_TEMP_CORE4 "TC4C" //CORE 4
#define SMC_KEY_CPU_TEMP_CORE5 "TC5C" //CORE 5
#define SMC_KEY_CPU_TEMP_CORE6 "TC6C" //CORE 6
#define SMC_KEY_CPU_TEMP_CORE7 "PC6C"
#define SMC_KEY_CPU_TEMP_CORE8 "PC7C"

//POWER

#define SMC_KEY_CPU_POWER_CORE1 "PC0C"
#define SMC_KEY_CPU_POWER_CORE2 "PC1C"
#define SMC_KEY_CPU_POWER_CORE3 "PC2C"
#define SMC_KEY_CPU_POWER_CORE4 "PC3C"
#define SMC_KEY_CPU_POWER_CORE5 "PC4C"
#define SMC_KEY_CPU_POWER_CORE6 "PC5C"
#define SMC_KEY_CPU_POWER_CORE7 "PC6C"
#define SMC_KEY_CPU_POWER_CORE8 "PC7C"


//***FAN

#define SMC_KEY_FAN0_CURRENT_SPEED "F0Ac"
#define SMC_KEY_FAN0_MINIMUM_SPEED "F0Mn"
#define SMC_KEY_FAN0_MAXIMUM_SPEED "F0Mx"
#define SMC_KEY_FAN0_MAXIMUM_SPEED "F0Mx"

#define SMC_KEY_FAN1_CURRENT_SPEED "F1Ac"
#define SMC_KEY_FAN1_MINIMUM_SPEED "F1Mn"
#define SMC_KEY_FAN1_MAXIMUM_SPEED "F1Mx"
#define SMC_KEY_FAN1_MAXIMUM_SPEED "F1Mx"

//***GPU
#define SMC_KEY_GPU_TEMP "TG0P"


//***BATTERY
#define SMC_KEY_BATTERY_AMPERAGE "B0AC"
#define SMC_KEY_BATTERY_VOLTAGE "B0AV"
#define SMC_KEY_BATTERY_CYCLECOUNT "B0CT"
//#define SMC_KEY_BATTERY_FULLCHARGE_CAPACITY "B0FC"
//#define SMC_KEY_BATTERY_REMAINING_CAPACITY "B0RM"

#define SMC_KEY_BATTERY_CELL1_VOLTAGE "BC1V"
#define SMC_KEY_BATTERY_CELL1_CAPACITY "BQX1"

#define SMC_KEY_BATTERY_CELL2_VOLTAGE "BC2V"
#define SMC_KEY_BATTERY_CELL2_CAPACITY "BQX2"

#define SMC_KEY_BATTERY_CELL3_VOLTAGE "BC3V"
#define SMC_KEY_BATTERY_CELL3_CAPACITY "BQX3"








#endif //CPUSTATS_KEYS_H
